export const GET_CATEGORIES_SEARCH = 'GET_CATEGORIES_SEARCH';
export const GET_CATEGORIES_BY_CODE = 'GET_CATEGORIES_BY_CODE';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';