export const GET_COURSES_SEARCH = "GET_COURSES_SEARCH";
export const GET_COURSES_SEARCH_PAGINATION = "GET_COURSES_SEARCH_PAGINATION";
export const GET_COURSE_BY_CODE_NAME = "GET_COURSE_BY_CODE_NAME";
export const GET_COURSE_ALL_FIELD_BY_CODE_NAME = "GET_COURSE_ALL_FIELD_BY_CODE_NAME";
export const DELETE_COURSE = "DELETE_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const CREATE_COURSE = "CREATE_COURSE";

