export const GET_COURSES_SEARCH = "GET_COURSES_SEARCH";
export const GET_COURSE_BY_CODE_NAME = "GET_COURSE_BY_CODE_NAME";
export const GET_COURSE_ALL_FIELD_BY_CODE_NAME = "GET_COURSE_ALL_FIELD_BY_CODE_NAME";

