export const DISCUSS_GET_SEARCH = "DISCUSS_GET_SEARCH";
export const DISCUSS_CREATE = "DISCUSS_CREATE";
export const DISCUSS_UPDATE = "DISCUSS_UPDATE";
export const DISCUSS_DELETE = "DISCUSS_DELETE";
