export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_FB = 'AUTH_LOGIN_FB';
export const AUTH_LOGIN_GG = 'AUTH_LOGIN_GG';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_FORGOT_PASS = 'AUTH_FORGOT_PASS';
export const AUTH_ACTIVE_COURSE = 'AUTH_ACTIVE_COURSE';
